basic.showIcon(IconNames.Heart)
SuperBit.Servo2(SuperBit.enServo.S1, 0)
SuperBit.Servo2(SuperBit.enServo.S1, 0)
SuperBit.Servo2(SuperBit.enServo.S1, 0)
SuperBit.Servo2(SuperBit.enServo.S1, 0)
basic.pause(1000)
basic.forever(function () {
    SuperBit.Servo2(SuperBit.enServo.S1, 0)
    SuperBit.Servo2(SuperBit.enServo.S1, 0)
    SuperBit.Servo2(SuperBit.enServo.S1, 0)
    SuperBit.Servo2(SuperBit.enServo.S1, 0)
    basic.pause(1000)
    SuperBit.Servo2(SuperBit.enServo.S1, 90)
    SuperBit.Servo2(SuperBit.enServo.S1, 90)
    SuperBit.Servo2(SuperBit.enServo.S1, 90)
    SuperBit.Servo2(SuperBit.enServo.S1, 90)
    basic.pause(1000)
    SuperBit.Servo2(SuperBit.enServo.S1, 180)
    SuperBit.Servo2(SuperBit.enServo.S1, 180)
    SuperBit.Servo2(SuperBit.enServo.S1, 180)
    SuperBit.Servo2(SuperBit.enServo.S1, 180)
    basic.pause(1000)
    SuperBit.Servo2(SuperBit.enServo.S1, 270)
    SuperBit.Servo2(SuperBit.enServo.S1, 270)
    SuperBit.Servo2(SuperBit.enServo.S1, 270)
    SuperBit.Servo2(SuperBit.enServo.S1, 270)
    basic.pause(1000)
    SuperBit.Servo2(SuperBit.enServo.S1, 180)
    SuperBit.Servo2(SuperBit.enServo.S1, 180)
    SuperBit.Servo2(SuperBit.enServo.S1, 180)
    SuperBit.Servo2(SuperBit.enServo.S1, 180)
    basic.pause(1000)
    SuperBit.Servo2(SuperBit.enServo.S1, 90)
    SuperBit.Servo2(SuperBit.enServo.S1, 90)
    SuperBit.Servo2(SuperBit.enServo.S1, 90)
    SuperBit.Servo2(SuperBit.enServo.S1, 90)
})
